name: helper_set
description: Helper packages
version: 0.0.1
homepage: https://github.com/IkhwanSI13/helper_set

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  path_provider: ^1.6.24
  flutter_image_compress: ^0.7.0
  cached_network_image: ^2.0.0
  url_launcher: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/images/
